version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  # A weekly update to rust dependencies. These will be grouped,
  # e.g. one PR will contain updates for all dependencies.
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  # Make it also update transitive dependencies in Cargo.lock
  allow:
    - dependency-type: "all"
  # Group all available updates into a group called "rust-dependencies"
  groups:
    rust-dependencies:
      patterns:
        - "*"