[workspace.package]
repository = "https://github.com/rust-vmm/rust-vmm"

[workspace]
members = [
  "acpi_tables",
  "event-manager",
  "kvm/kvm-bindings",
  "kvm/kvm-ioctls",
  "linux-loader",
  "seccompiler",
  "vm-allocator",
  "vm-memory",
  "vm-superio",
  "vm-superio-ser",
  "vmm-sys-util",
  "vm-virtio/virtio-bindings",
  "vm-virtio/virtio-blk",
  "vm-virtio/virtio-console",
  "vm-virtio/virtio-device",
  "vm-virtio/virtio-queue",
  "vm-virtio/virtio-queue-ser",
  "vm-virtio/virtio-vsock",
]
resolver = "2"

# When running benchmark it's convenient to run with lto=true and codegen-units=1.
# While these might increase the build time, it may also produce faster code. These
# options are typically used in release binaries as well.
[profile.bench]
lto = true
codegen-units = 1

[workspace.dependencies]
vm-memory = { version = "0.18.0", path = "vm-memory" }
vmm-sys-util = { version = "0.15.0", path = "vmm-sys-util" }

virtio-bindings = { version = "0.2.7", path = "vm-virtio/virtio-bindings" }
virtio-device = { version = "0.1.0", path = "vm-virtio/virtio-device" }
virtio-queue = { version = "0.18.0", path = "vm-virtio/virtio-queue" }
virtio-queue-ser = { version = "0.14.0", path = "vm-virtio/virtio-queue-ser" }
