name: Publish event-manager to crates.io

on:
  push:
    tags: ['event-manager-v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish --package event-manager
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}